#!/bin/sh

USER_NAME="example"
USER_WEB="example"


echo "$USER_NAME"

"""Adding USER to groups """
sudo adduser "$USER_NAME" web
sudo adduser "$USER_NAME" www-data


"""Creating folders for web"""
mkdir -p /home/"$USER_NAME"/www
mkdir -p /var/www/wedevs.sk/public_html/"$USER_WEB"


"""Creating symlink to folder /var/www/"""
ln -s /var/www/wedevs.sk/public_html/"$USER_WEB" /home/"$USER_NAME"/www




